/**
 * Single source of truth for all user-facing website copy.
 *
 * Add or edit translatable text here. HTML elements reference values with
 * data-copy keys; do not place user-facing copy directly in HTML or site.js.
 */
window.BIOARCHAI_CONTENT = {
  "shared": {
    "locale": "en",
    "brand": "BioArchai",
    "brandHomeAria": "BioArchai home",
    "openNavigationAria": "Open navigation",
    "footerNavigationAria": "Footer navigation",
    "navHome": "Home",
    "navPlatform": "Platform",
    "navSolutions": "Solutions",
    "navApplications": "Applications",
    "navMission": "Mission",
    "navTeam": "Team",
    "navNews": "News",
    "navCareers": "Careers",
    "requestDemo": "Request a Demo",
    "requestDemoShort": "Request Demo",
    "contactBioArchai": "Contact BioArchai",
    "archaiNexus": "Archai Nexus",
    "txArchai": "Tx Archai",
    "dxArchai": "Dx Archai",
    "evidenceArchai": "Evidence Archai",
    "primary": "Primary",
    "supporting": "Supporting",
    "comingSoon": "Coming soon",
    "copyright": "© 2026 BioArchai. Precision medicine intelligence, built for expert judgment.",
    "contactMailto": "mailto:nastaran.hida@gmail.com",
    "value01": "01",
    "value02": "02",
    "value03": "03",
    "value04": "04",
    "biomarkerStrategy": "Biomarker Strategy",
    "identifyPrioritizeAndContextualizeBiomarkersBasedOnDiseaseBiology": "Identify, prioritize, and contextualize biomarkers based on disease biology, clinical relevance, competitive landscape, assay feasibility, and development value.",
    "planEvidencePackagesThatSupportClinicalUtilityMedicalValue": "Plan evidence packages that support clinical utility, medical value, diagnostic adoption, stakeholder confidence, and value communication.",
    "bioarchaiApplicationsArePoweredByArchaiNexusAndTailored": "BioArchai applications are powered by Archai Nexus and tailored to therapeutic, diagnostic, and evidence-generation teams.",
    "diagnosticAndAssayStrategy": "Diagnostic and assay strategy",
    "bringBiologicalReasoningAndAiNativeWorkflowIntelligenceTogether": "Bring biological reasoning and AI-native workflow intelligence together.",
    "whyBiomarkerStrategyNeedsDiseaseSpecificIntelligence": "Why biomarker strategy needs disease-specific intelligence",
    "fromEvidenceFragmentsToDecisionReadyOutputs": "From evidence fragments to decision-ready outputs",
    "designPartnerOpportunitiesForArchaiNexus": "Design partner opportunities for Archai Nexus",
    "buildTheFutureOfAiEnabledPrecisionMedicine": "Build the future of AI-enabled precision medicine.",
    "biomarkerBasedClinicalTrialPlanning": "Biomarker-Based Clinical Trial Planning",
    "diagnosticAndAssayStrategy2": "Diagnostic and Assay Strategy",
    "biomarkerBasedEvidenceGeneration": "Biomarker-Based Evidence Generation"
  },
  "home": {
    "bioarchaiAgenticAiForBiomarkerDrivenPrecisionMedicine": "BioArchai | Agentic AI for Biomarker-Driven Precision Medicine",
    "bioarchaiArchaiNexustm": "BioArchai / Archai Nexus™",
    "agenticAiForBiomarkerDrivenPrecisionMedicine": "Agentic AI for Biomarker-Driven Precision Medicine",
    "bioarchaiBuildsDiseaseSpecificIntelligenceSolutionsThatHelpBiopharma": "BioArchai builds disease-specific intelligence solutions that help biopharma teams transform complex biological evidence into explainable, decision-ready strategy.",
    "exploreArchaiNexus": "Explore Archai Nexus",
    "evidenceData": "Evidence + Data",
    "biologicalEvidence": "Biological evidence",
    "clinicalContext": "Clinical context",
    "assaySignals": "Assay signals",
    "unifyingIntelligenceLayer": "Unifying intelligence layer",
    "decisionOutputs": "Decision Outputs",
    "prioritizedBiomarkers": "Prioritized biomarkers",
    "trialRationales": "Trial rationales",
    "evidenceRoadmaps": "Evidence roadmaps",
    "theIntelligenceLayerBehindBioarchai": "The Intelligence Layer Behind BioArchai",
    "archaiNexusConnectsBiologicalEvidenceBiomarkersAssaysClinicalContext": "Archai Nexus connects biological evidence, biomarkers, assays, clinical context, and expert decision logic to power BioArchai applications across therapeutic development, diagnostics, and evidence generation.",
    "evidenceInputs": "Evidence Inputs",
    "biologicalLiteratureClinicalDataBiomarkerLandscapesAssayConstraintsStandards": "Biological literature, clinical data, biomarker landscapes, assay constraints, standards, and stakeholder needs.",
    "diseaseSpecificEvidenceSynthesisTraceabilityExpertLogicConfigurableScoring": "Disease-specific evidence synthesis, traceability, expert logic, configurable scoring, and decision support workflows.",
    "solutionsApplications": "Solutions + Applications",
    "biomarkerStrategyTrialPlanningAssayStrategyEvidenceGenerationAnd": "Biomarker strategy, trial planning, assay strategy, evidence generation, and team-configured product experiences.",
    "decisionReadyOutputs": "Decision-Ready Outputs",
    "prioritizedRecommendationsEvidenceSummariesRiskFlagsRoadmapsAndStakeholder": "Prioritized recommendations, evidence summaries, risk flags, roadmaps, and stakeholder-ready reports.",
    "biomarkerIntelligenceAcrossStrategyTrialsAssaysAndEvidence": "Biomarker Intelligence Across Strategy, Trials, Assays, and Evidence",
    "bioarchaiSupportsDiseaseSpecificWorkflowsAcrossThePrecisionMedicine": "BioArchai supports disease-specific workflows across the precision medicine lifecycle, powered by Archai Nexus.",
    "workflow": "Workflow",
    "viewWorkflow": "View workflow",
    "clinicalTrialPlanning": "Clinical Trial Planning",
    "supportTranslationalAndClinicalTeamsInPlanningBiomarkerInformed": "Support translational and clinical teams in planning biomarker-informed development strategies from early clinical hypotheses through Phase I-III decisions.",
    "diagnosticAssayStrategy": "Diagnostic & Assay Strategy",
    "evaluateAssayOptionsAndTestingPathwaysNeededToSupport": "Evaluate assay options and testing pathways needed to support biomarker-driven programs with vendor-agnostic strategy and implementation risk flags.",
    "evidenceGeneration": "Evidence Generation",
    "configuredForTheTeamsDrivingPrecisionMedicine": "Configured for the Teams Driving Precision Medicine",
    "forPharmaTranslationalBiomarkerAndClinicalTrialTeamsMoving": "For pharma translational, biomarker, and clinical trial teams moving from biological rationale and fragmented evidence to biomarker-informed clinical strategy.",
    "biomarkerStrategy": "Biomarker strategy",
    "patientEnrichment": "Patient enrichment",
    "phaseIIiiDecisionSupport": "Phase I-III decision support",
    "exploreTxArchai": "Explore Tx Archai",
    "forDiagnosticsAssayPlanningAndBiopharmaPartnershipTeamsTranslating": "For diagnostics, assay planning, and biopharma partnership teams translating testing capabilities and biomarker data into pharma-facing strategy.",
    "cdxIvdPlanningSupport": "CDx / IVD planning support",
    "partnershipEvidencePackages": "Partnership evidence packages",
    "exploreDxArchai": "Explore Dx Archai",
    "forMedicalAffairsHeorRweAndEvidenceGenerationTeams": "For Medical Affairs, HEOR, RWE, and evidence generation teams shaping stakeholder-ready strategies for scientific engagement and value communication.",
    "clinicalUtilityEvidence": "Clinical utility evidence",
    "rweStudyConcepts": "RWE study concepts",
    "medicalAndValueNarratives": "Medical and value narratives",
    "exploreEvidenceArchai": "Explore Evidence Archai",
    "whyBioarchai": "Why BioArchai",
    "builtForBiologicalComplexityDesignedForExpertJudgment": "Built for Biological Complexity. Designed for Expert Judgment.",
    "bioarchaiIsDesignedForTeamsWhoNeedExplainableDisease": "BioArchai is designed for teams who need explainable, disease-specific reasoning rather than generic AI summaries or disconnected evidence repositories.",
    "diseaseSpecificIntelligence": "Disease-specific intelligence",
    "contextualReasoningShapedAroundDiseaseBiologyClinicalRealityAnd": "Contextual reasoning shaped around disease biology, clinical reality, and biomarker maturity.",
    "evidenceTraceability": "Evidence traceability",
    "outputsAreGroundedInSourceableEvidenceRationaleAndClear": "Outputs are grounded in sourceable evidence, rationale, and clear decision logic.",
    "humanInTheLoop": "Human-in-the-loop",
    "builtForExpertReviewCalibrationAndJudgmentAtThe": "Built for expert review, calibration, and judgment at the points where decisions matter.",
    "configurableScoring": "Configurable scoring",
    "supportForDiseaseStageEvidenceAssayAndStakeholderSpecific": "Support for disease, stage, evidence, assay, and stakeholder-specific criteria.",
    "vendorAgnosticStrategy": "Vendor-agnostic strategy",
    "assayAndDiagnosticPathwaysCanBeEvaluatedWithoutForcing": "Assay and diagnostic pathways can be evaluated without forcing a single vendor lens.",
    "decisionReadyReports": "Decision-ready reports",
    "recommendationsEvidenceSummariesGapsAndNextStepsPackagedFor": "Recommendations, evidence summaries, gaps, and next steps packaged for team alignment.",
    "bioarchaiExistsToImprovePrecisionMedicineAndDrugDevelopment": "BioArchai exists to improve precision medicine and drug development decisions by helping teams move from fragmented biological and clinical evidence to clearer, explainable, biomarker-driven strategy.",
    "readTheMission": "Read the mission",
    "builtByExpertsAcrossPrecisionMedicineGenomicsOncologyDiagnostics": "Built by experts across precision medicine, genomics, oncology, diagnostics, and AI product strategy.",
    "theFirstVersionIncludesFounderAndAdvisorPlaceholdersSo": "The first version includes founder and advisor placeholders so BioArchai can add profiles as the team page is finalized.",
    "viewTeam": "View team",
    "insights": "Insights",
    "latestThinkingFromBioarchai": "Latest Thinking from BioArchai",
    "visitNews": "Visit News",
    "perspective": "Perspective",
    "aForthcomingPerspectiveOnConnectingMechanismClinicalContextAnd": "A forthcoming perspective on connecting mechanism, clinical context, and assay feasibility.",
    "platformNote": "Platform Note",
    "aPracticalViewOfTraceabilityPrioritizationAndExpertReview": "A practical view of traceability, prioritization, and expert review in biomarker workflows.",
    "companyUpdate": "Company Update",
    "bioarchaiIsPreparingEarlyCollaborationPathwaysForQualifiedBiopharma": "BioArchai is preparing early collaboration pathways for qualified biopharma and diagnostic teams.",
    "bioarchaiIsNotListingOpenRolesYetButThe": "BioArchai is not listing open roles yet, but the careers page is ready for future opportunities and relevant introductions.",
    "readyToExploreArchaiNexus": "Ready to explore Archai Nexus?",
    "startAStrategyDiscussionWithBioarchai": "Start a strategy discussion with BioArchai.",
    "evidenceAndDataFlowThroughArchaiNexusIntoDecision": "Evidence and data flow through Archai Nexus into decision-ready outputs",
    "evidenceInputsFlowIntoArchaiNexusAndBecomeSolutions": "Evidence inputs flow into Archai Nexus and become solutions, applications, and reports"
  },
  "platform": {
    "archaiNexusPlatformBioarchai": "Archai Nexus Platform | BioArchai",
    "archaiNexustm": "Archai Nexus™",
    "theIntelligenceLayerForDiseaseSpecificBiomarkerDecisions": "The Intelligence Layer for Disease-Specific Biomarker Decisions",
    "archaiNexusConnectsBiologicalEvidenceClinicalContextBiomarkerData": "Archai Nexus connects biological evidence, clinical context, biomarker data, assay considerations, evidence standards, and expert decision logic into decision-ready outputs.",
    "evidenceDataToDecisions": "Evidence + Data to Decisions",
    "designedAsTheUnifyingLayerBehindBioarchaiSolutionsAnd": "Designed as the unifying layer behind BioArchai solutions and configured applications.",
    "value01EvidenceInputs": "01. Evidence Inputs",
    "biologicalEvidence": "Biological Evidence",
    "diseaseBiologyMechanismsOfActionBiomarkerLiteratureOmicsAnd": "Disease biology, mechanisms of action, biomarker literature, omics, and translational rationale.",
    "clinicalContext": "Clinical Context",
    "trialOutcomesPatientCohortsLabelsCompetitorProgramsCarePathways": "Trial outcomes, patient cohorts, labels, competitor programs, care pathways, and stakeholder needs.",
    "assayConsiderations": "Assay Considerations",
    "testingPathwaysSampleTypesCutoffConsiderationsReadinessAndImplementation": "Testing pathways, sample types, cutoff considerations, readiness, and implementation risks.",
    "thePlatformLayerThatMakesEvidenceConnectedExplainableAnd": "The platform layer that makes evidence connected, explainable, and configurable for disease-specific biomarker workflows.",
    "evidenceTraceability": "Evidence Traceability",
    "expertDecisionLogic": "Expert Decision Logic",
    "diseaseContext": "Disease Context",
    "configurableScoring": "Configurable Scoring",
    "value03Outputs": "03. Outputs",
    "decisionReadyReports": "Decision-Ready Reports",
    "executiveSummariesRationaleEvidenceGapsStrategyRecommendationsAndStakeholder": "Executive summaries, rationale, evidence gaps, strategy recommendations, and stakeholder-ready outputs.",
    "prioritizedBiomarkers": "Prioritized Biomarkers",
    "rankedCandidatesWithBiologicalRationaleEvidenceConfidenceAndDevelopment": "Ranked candidates with biological rationale, evidence confidence, and development-value context.",
    "evidenceRoadmaps": "Evidence Roadmaps",
    "clinicalUtilityFrameworksEvidenceGenerationPlansAndMedicalOr": "Clinical utility frameworks, evidence generation plans, and medical or value communication inputs.",
    "platformRole": "Platform Role",
    "archaiNexusPowersSolutionsAndApplicationsWithoutBecomingA": "Archai Nexus powers solutions and applications without becoming a separate consulting layer.",
    "thePlatformSitsBehindBioarchaiWorkflowsTranslatingFragmentedScientific": "The platform sits behind BioArchai workflows, translating fragmented scientific, clinical, diagnostic, and evidence inputs into outputs that teams can inspect, challenge, and use for planning.",
    "connectsEvidenceDomains": "Connects evidence domains",
    "biologyClinicalContextAssayReadinessEvidenceStandardsAndExpert": "Biology, clinical context, assay readiness, evidence standards, and expert logic are treated as connected decision inputs.",
    "supportsConfigurableReasoning": "Supports configurable reasoning",
    "scoringCriteriaCanBeTunedByDiseaseAreaDevelopment": "Scoring criteria can be tuned by disease area, development stage, stakeholder, and evidence confidence.",
    "keepsExpertReviewCentral": "Keeps expert review central",
    "outputsAreDesignedForExpertJudgmentReviewAndStrategy": "Outputs are designed for expert judgment, review, and strategy discussions, not black-box automation.",
    "exploreThePlatform": "Explore the Platform",
    "seeHowArchaiNexusCanSupportADiseaseSpecific": "See how Archai Nexus can support a disease-specific biomarker workflow.",
    "archaiNexusIsTheUnifyingIntelligenceLayerForDisease": "Archai Nexus is the unifying intelligence layer for disease-specific biomarker decisions.",
    "archaiNexusPlatformArchitecture": "Archai Nexus platform architecture"
  },
  "solutions": {
    "solutionsBioarchai": "Solutions | BioArchai",
    "biomarkerIntelligenceAcrossThePrecisionMedicineLifecycle": "Biomarker Intelligence Across the Precision Medicine Lifecycle",
    "bioarchaiSupportsDiseaseSpecificDecisionWorkflowsAcrossBiomarkerStrategy": "BioArchai supports disease-specific decision workflows across biomarker strategy, biomarker-based clinical trial planning, diagnostic and assay strategy, and biomarker-based evidence generation - powered by Archai Nexus.",
    "value4WorkflowLayers": "4 workflow layers",
    "clearCapabilitiesThatCanSupportTherapeuticDiagnosticAndEvidence": "Clear capabilities that can support therapeutic, diagnostic, and evidence-generation teams.",
    "workflow01": "Workflow 01",
    "includes": "Includes",
    "biomarkerPrioritization": "Biomarker prioritization",
    "diseaseSpecificBiomarkerLandscape": "Disease-specific biomarker landscape",
    "mechanismOfActionAlignment": "Mechanism-of-action alignment",
    "patientSegmentationAndTranslationalRationale": "Patient segmentation and translational rationale",
    "exampleOutputs": "Example outputs",
    "rankedBiomarkerList": "Ranked biomarker list",
    "evidenceSummary": "Evidence summary",
    "biologicalRationale": "Biological rationale",
    "strategyRecommendation": "Strategy recommendation",
    "workflow02": "Workflow 02",
    "supportTranslationalAndClinicalTeamsInPlanningBiomarkerInformed": "Support translational and clinical teams in planning biomarker-informed development strategies across patient enrichment, evidence, feasibility, and competitive dynamics.",
    "patientEnrichmentRationale": "Patient enrichment rationale",
    "biomarkerInformedInclusionAndExclusion": "Biomarker-informed inclusion and exclusion",
    "trialLandscapeAndCompetitorBenchmarking": "Trial landscape and competitor benchmarking",
    "recruitmentAndPrevalenceFeasibility": "Recruitment and prevalence feasibility",
    "trialPlanningSummary": "Trial planning summary",
    "competitorBenchmark": "Competitor benchmark",
    "assayAndTestingConsiderations": "Assay and testing considerations",
    "developmentStageRecommendation": "Development-stage recommendation",
    "workflow03": "Workflow 03",
    "evaluateAssayOptionsAndTestingPathwaysNeededToSupport": "Evaluate assay options and testing pathways needed to support biomarker-driven programs, including CDx, IVD, vendor landscape, and implementation risks.",
    "assayLandscapeReview": "Assay landscape review",
    "vendorAgnosticTestRecommendations": "Vendor-agnostic test recommendations",
    "cutoffAndSampleTypeConsiderations": "Cutoff and sample type considerations",
    "assayReadinessAndImplementationRisk": "Assay readiness and implementation risk",
    "assayRecommendationSummary": "Assay recommendation summary",
    "diagnosticPathwayConsiderations": "Diagnostic pathway considerations",
    "vendorAndTestLandscape": "Vendor and test landscape",
    "cutoffAndSampleTypeRiskFlags": "Cutoff and sample-type risk flags",
    "workflow04": "Workflow 04",
    "evidenceGapAnalysis": "Evidence gap analysis",
    "clinicalUtilityStrategy": "Clinical utility strategy",
    "rweOpportunityAssessment": "RWE opportunity assessment",
    "medicalAndScientificNarrativeSupport": "Medical and scientific narrative support",
    "evidenceGenerationRoadmap": "Evidence generation roadmap",
    "clinicalUtilityFramework": "Clinical utility framework",
    "valueNarrative": "Value narrative",
    "stakeholderReadySummary": "Stakeholder-ready summary",
    "workflowStrategy": "Workflow Strategy",
    "discussWhichBiomarkerWorkflowMapsToYourTeam": "Discuss which biomarker workflow maps to your team.",
    "bioarchaiSupportsBiomarkerStrategyBiomarkerBasedClinicalTrialPlanning": "BioArchai supports biomarker strategy, biomarker-based clinical trial planning, diagnostic and assay strategy, and biomarker-based evidence generation."
  },
  "applications": {
    "applicationsBioarchai": "Applications | BioArchai",
    "applicationsConfiguredForTheTeamsDrivingPrecisionMedicine": "Applications Configured for the Teams Driving Precision Medicine",
    "txDxEvidence": "Tx / Dx / Evidence",
    "threeProductExperiencesThatKeepBuyerContextClearWhile": "Three product experiences that keep buyer context clear while sharing the same intelligence layer.",
    "therapeuticTeams": "Therapeutic Teams",
    "txArchaiHelpsDrugDevelopmentTeamsMoveFromBiological": "Tx Archai helps drug development teams move from biological rationale and fragmented evidence to biomarker-informed clinical strategy.",
    "primaryUsers": "Primary users",
    "pharmaTranslationalBiomarkerAndClinicalTrialTeams": "Pharma translational, biomarker, and clinical trial teams.",
    "supports": "Supports",
    "biomarkerStrategyAndTranslationalPlanning": "Biomarker strategy and translational planning",
    "biomarkerBasedClinicalTrialPlanning": "Biomarker-based clinical trial planning",
    "patientEnrichmentAndPhaseIIiiDecisionSupport": "Patient enrichment and Phase I-III decision support",
    "assayAndCutoffFeasibility": "Assay and cutoff feasibility",
    "diagnosticTeams": "Diagnostic Teams",
    "dxArchaiHelpsDiagnosticsAndAssayTeamsTranslateTesting": "Dx Archai helps diagnostics and assay teams translate testing capabilities, assay evidence, and biomarker data into pharma-facing strategy and partnership value.",
    "diagnosticsAssayPlanningAndBiopharmaPartnershipTeams": "Diagnostics, assay planning, and biopharma partnership teams.",
    "internalTestingDataIntelligence": "Internal testing data intelligence",
    "cdxIvdPlanningAndVendorLandscape": "CDx / IVD planning and vendor landscape",
    "trialSupportAndDiagnosticFeasibility": "Trial support and diagnostic feasibility",
    "evidenceTeams": "Evidence Teams",
    "evidenceArchaiHelpsTeamsTransformBiomarkerTrialLabelPublication": "Evidence Archai helps teams transform biomarker, trial, label, publication, RWE, and access evidence into stakeholder-ready strategies.",
    "medicalAffairsHeorRweAndEvidenceGenerationTeams": "Medical Affairs, HEOR, RWE, and evidence generation teams.",
    "clinicalUtilityAndValueEvidence": "Clinical utility and value evidence",
    "kolAndAdvisoryBoardPreparation": "KOL and advisory board preparation",
    "rweStudyConceptsAndAccessGaps": "RWE study concepts and access gaps",
    "postLaunchEvidenceStrategy": "Post-launch evidence strategy",
    "workflowMapping": "Workflow Mapping",
    "howSolutionsMapToApplications": "How solutions map to applications",
    "applicationsAreConfiguredForDifferentTeamsWhileTheWorkflow": "Applications are configured for different teams, while the workflow solutions remain shared capabilities.",
    "workflowSolution": "Workflow / Solution",
    "medicalScientificEngagement": "Medical / Scientific Engagement",
    "rweHeorValueEvidence": "RWE / HEOR / Value Evidence",
    "pharmaPartnershipEvidence": "Pharma Partnership Evidence",
    "applicationFit": "Application Fit",
    "findTheBioarchaiApplicationThatBestMapsToYour": "Find the BioArchai application that best maps to your team."
  },
  "mission": {
    "missionBioarchai": "Mission | BioArchai",
    "bioarchaiHelpsPrecisionMedicineTeamsMoveFromFragmentedBiological": "BioArchai helps precision medicine teams move from fragmented biological and clinical evidence to clearer, explainable, biomarker-driven decisions across therapeutic development, diagnostics, and evidence generation.",
    "verticalAiForBiologicalComplexity": "Vertical AI for biological complexity",
    "designedForExpertLedDecisionsWhereContextTraceabilityAnd": "Designed for expert-led decisions where context, traceability, and disease specificity matter.",
    "companyPhilosophy": "Company Philosophy",
    "precisionMedicineNeedsAiThatRespectsTheComplexityOf": "Precision medicine needs AI that respects the complexity of biology.",
    "bioarchaiIsBuiltAroundTheIdeaThatBetterBiomarker": "BioArchai is built around the idea that better biomarker decisions require connected evidence, explicit reasoning, and workflows shaped by the teams making the decisions. The goal is not to replace expert judgment, but to give it stronger, more inspectable intelligence.",
    "startWithDiseaseContext": "Start with disease context",
    "biomarkerDecisionsDependOnBiologyPatientPopulationsCarePathways": "Biomarker decisions depend on biology, patient populations, care pathways, evidence maturity, and program strategy. BioArchai treats that context as foundational.",
    "makeEvidenceTraceable": "Make evidence traceable",
    "teamsNeedToUnderstandWhyARecommendationExistsBioarchai": "Teams need to understand why a recommendation exists. BioArchai emphasizes sourceable evidence, rationale, confidence, gaps, and risk flags.",
    "designForExpertReview": "Design for expert review",
    "outputsShouldBeReadyForTranslationalScienceClinicalDiagnostic": "Outputs should be ready for translational science, clinical, diagnostic, medical affairs, and HEOR discussions, with humans in the loop.",
    "moveTowardDecisionReadyStrategy": "Move toward decision-ready strategy",
    "theProductExperienceIsOrientedAroundPracticalOutputsPrioritization": "The product experience is oriented around practical outputs: prioritization, planning summaries, evidence roadmaps, and stakeholder-ready communication.",
    "principles": "Principles",
    "howBioarchaiShouldFeelToATeamUsingIt": "How BioArchai should feel to a team using it",
    "premiumAndScientificButPragmaticEnoughToSupportReal": "Premium and scientific, but pragmatic enough to support real workflows and strategic alignment.",
    "explainable": "Explainable",
    "outputsPreserveTheReasoningPathSoTeamsCanInspect": "Outputs preserve the reasoning path so teams can inspect, challenge, and refine recommendations.",
    "configurable": "Configurable",
    "workflowsCanAdaptByDiseaseAreaDevelopmentStageStakeholder": "Workflows can adapt by disease area, development stage, stakeholder needs, and evidence standards.",
    "connected": "Connected",
    "biologicalClinicalDiagnosticAndValueEvidenceBecomePartOf": "Biological, clinical, diagnostic, and value evidence become part of one decision framework.",
    "bioarchaiBringsBiologicalReasoningClinicalContextAndAiNative": "BioArchai brings biological reasoning, clinical context, and AI-native workflow intelligence together to improve precision medicine decisions."
  },
  "team": {
    "teamBioarchai": "Team | BioArchai",
    "expertiseAcrossPrecisionMedicineGenomicsOncologyDiagnosticsAndAi": "Expertise across precision medicine, genomics, oncology, diagnostics, and AI product strategy.",
    "thisPageIsStructuredForFounderAdvisorAndTeam": "This page is structured for founder, advisor, and team profiles as BioArchai finalizes public bios.",
    "credibilityFirst": "Credibility first",
    "designedToSupportExecutiveTranslationalScienceDiagnosticAndInvestor": "Designed to support executive, translational science, diagnostic, and investor audiences.",
    "founderProfile": "Founder Profile",
    "founder": "Founder",
    "founderBioPlaceholderForPrecisionMedicineBiomarkerStrategyTranslational": "Founder bio placeholder for precision medicine, biomarker strategy, translational science, diagnostics, and AI product leadership. Replace with a finalized public profile when approved.",
    "precisionMedicine": "Precision Medicine",
    "aiProduct": "AI Product",
    "advisorPlaceholder": "Advisor Placeholder",
    "scientificAdvisor": "Scientific Advisor",
    "advisorProfilePlaceholderForGenomicsOncologyTranslationalBiologyAnd": "Advisor profile placeholder for genomics, oncology, translational biology, and disease-specific biomarker expertise.",
    "genomics": "Genomics",
    "oncology": "Oncology",
    "translationalBiology": "Translational Biology",
    "evidenceAdvisor": "Evidence Advisor",
    "advisorProfilePlaceholderForMedicalAffairsHeorRweClinical": "Advisor profile placeholder for Medical Affairs, HEOR, RWE, clinical utility, payer value, and evidence generation.",
    "heor": "HEOR",
    "rwe": "RWE",
    "evidenceStrategy": "Evidence Strategy",
    "advisoryNetwork": "Advisory Network",
    "bioarchaiIsDesignedForCollaborationWithExpertsAndEarly": "BioArchai is designed for collaboration with experts and early design partners.",
    "useThisPageToAddAdvisorProfilesInstitutionalExpertise": "Use this page to add advisor profiles, institutional expertise, and partner-facing credibility as they become public.",
    "discussPartnership": "Discuss Partnership",
    "bioarchaiIsBuiltByExpertsAcrossPrecisionMedicineGenomics": "BioArchai is built by experts across precision medicine, genomics, oncology, diagnostics, and AI product strategy."
  },
  "news": {
    "newsBlogBioarchai": "News & Blog | BioArchai",
    "newsBlog": "News & Blog",
    "latestThinkingFromBioarchai": "Latest thinking from BioArchai.",
    "thoughtLeadershipAndCompanyUpdatesForBiomarkerStrategyAi": "Thought leadership and company updates for biomarker strategy, AI-enabled precision medicine, diagnostic planning, and evidence generation.",
    "value3StarterArticles": "3 starter articles",
    "readyToUpdatePlaceholdersForEarlyPerspectivePiecesAnd": "Ready-to-update placeholders for early perspective pieces and company announcements.",
    "aForthcomingPerspectiveOnWhyMechanismClinicalContextAssay": "A forthcoming perspective on why mechanism, clinical context, assay feasibility, and evidence confidence need to be considered together.",
    "discussThisTopic": "Discuss this topic",
    "aPlatformNoteOnTraceableSynthesisConfigurableScoringAnd": "A platform note on traceable synthesis, configurable scoring, and expert review for high-stakes biomarker workflows.",
    "explorePlatform": "Explore platform",
    "anUpcomingCompanyUpdateForQualifiedBiopharmaDiagnosticMedical": "An upcoming company update for qualified biopharma, diagnostic, Medical Affairs, HEOR, and evidence-generation teams.",
    "requestADiscussion": "Request a discussion",
    "bioarchaiThoughtLeadershipAndCompanyUpdates": "BioArchai thought leadership and company updates."
  },
  "careers": {
    "careersBioarchai": "Careers | BioArchai",
    "bioarchaiIsPreparingTheFoundationForAMultidisciplinaryTeam": "BioArchai is preparing the foundation for a multidisciplinary team across precision medicine, AI product, engineering, biomarker strategy, and evidence generation.",
    "noOpenRolesCurrently": "No open roles currently",
    "futureOpportunitiesAndRelevantIntroductionsCanBeRoutedThrough": "Future opportunities and relevant introductions can be routed through the contact path.",
    "precisionMedicine": "Precision medicine",
    "futureRolesMayIncludeBiomarkerStrategyTranslationalScienceClinical": "Future roles may include biomarker strategy, translational science, clinical evidence, diagnostics, and disease-area expertise.",
    "aiProductAndEngineering": "AI product and engineering",
    "futureRolesMayIncludeProductDesignAiWorkflowEngineering": "Future roles may include product design, AI workflow engineering, data infrastructure, and explainable decision systems.",
    "evidenceGeneration": "Evidence generation",
    "futureRolesMayIncludeMedicalAffairsHeorRweStrategy": "Future roles may include Medical Affairs, HEOR, RWE strategy, clinical utility, and value evidence expertise.",
    "stayConnected": "Stay Connected",
    "interestedInFutureOpportunities": "Interested in future opportunities?",
    "sendANoteWithYourBackgroundAreaOfInterest": "Send a note with your background, area of interest, and why BioArchai's mission is relevant to your work.",
    "buildTheFutureOfAiEnabledPrecisionMedicineWith": "Build the future of AI-enabled precision medicine with BioArchai.",
    "nastaranHidaGmailComSubjectBioarchai20careers20interest": "mailto:nastaran.hida@gmail.com?subject=BioArchai%20careers%20interest"
  },
  "demo": {
    "requestADemoBioarchai": "Request a Demo | BioArchai",
    "exploreArchaiNexusWithBioarchai": "Explore Archai Nexus with BioArchai.",
    "shareYourTeamContextDiseaseAreaOrWorkflowPriority": "Share your team context, disease area, or workflow priority and BioArchai will follow up about a demo, strategy discussion, or partnership conversation.",
    "qualifiedConversations": "Qualified conversations",
    "forBiopharmaExecutivesTranslationalLeadersBiomarkerTeamsDiagnosticPartners": "For biopharma executives, translational leaders, biomarker teams, diagnostic partners, Medical Affairs, HEOR, RWE, investors, and design partners.",
    "leadCapture": "Lead Capture",
    "tellUsWhatYouAreExploring": "Tell us what you are exploring.",
    "qualifiedRequestsCanFocusOnPlatformFitSolutionWorkflow": "Qualified requests can focus on platform fit, solution workflow, application fit, disease area, or partnership context.",
    "nastaranHidaGmailCom": "nastaran.hida@gmail.com",
    "returnToBioarchai": "Return to BioArchai",
    "name": "Name",
    "company": "Company",
    "titleRole": "Title / Role",
    "workEmail": "Work email",
    "areaOfInterest": "Area of interest",
    "selectAnArea": "Select an area",
    "archaiNexusPlatform": "Archai Nexus platform",
    "txArchaiTranslationalBiomarkerClinicalTrialPlanning": "Tx Archai: translational / biomarker / clinical trial planning",
    "dxArchaiDiagnosticsAssayStrategyBiopharmaPartnership": "Dx Archai: diagnostics / assay strategy / biopharma partnership",
    "evidenceArchaiMedicalAffairsHeorRweEvidenceGeneration": "Evidence Archai: Medical Affairs / HEOR / RWE / evidence generation",
    "advisoryPartnership": "Advisory / Partnership",
    "other": "Other",
    "therapeuticAreaOrDiseaseAreaOfInterest": "Therapeutic area or disease area of interest",
    "messageUseCase": "Message / use case",
    "submitRequest": "Submit Request",
    "bioarchaiWillFollowUpByEmail": "BioArchai will follow up by email.",
    "requestABioarchaiDemoOrStrategyDiscussion": "Request a BioArchai demo or strategy discussion.",
    "optional": "Optional",
    "email": {
      "recipient": "nastaran.hida@gmail.com",
      "subject": "BioArchai demo request",
      "fields": {
        "name": "Name",
        "company": "Company",
        "title": "Title / Role",
        "email": "Work email",
        "interest": "Area of interest",
        "disease": "Therapeutic / disease area",
        "message": "Message / use case"
      },
      "status": "Opening your email client with the request details."
    }
  }
};
